DEFAULT_NODES = [
    # (nama, potensi_pasar, biaya_sewa, kompetitor, aksesibilitas, keterangan)
    ("Kuta",                9.5, 35, 8, 9.0, "Kawasan wisata premium, traffic tinggi, sewa mahal"),
    ("Seminyak",            9.0, 40, 7, 8.5, "Pusat lifestyle & F&B kelas atas"),
    ("Denpasar Barat",      8.0, 20, 6, 8.0, "Pusat kota, akses mudah, pasar lokal besar"),
    ("Denpasar Timur",      7.5, 18, 5, 7.5, "Kawasan residensial yang berkembang"),
    ("Canggu",              8.5, 30, 6, 7.0, "Populer di kalangan expat & digital nomad"),
    ("Ubud",                7.0, 22, 4, 6.5, "Wisata budaya & wellness, niche market"),
    ("Sanur",               8.0, 25, 5, 8.0, "Kawasan wisata keluarga, stabil"),
    ("Denpasar Selatan",    8.5, 22, 5, 8.5, "Dekat bandara, kawasan bisnis & residensial yang padat"),
    ("Jimbaran",            7.5, 28, 4, 7.5, "Seafood & resort area, berkembang"),
    ("Nusa Dua",            7.0, 32, 3, 8.5, "MICE & luxury tourism, low kompetitor"),
    ("Kerobokan",           8.0, 26, 6, 7.5, "Transisi Kuta-Canggu, pasar campuran"),
    ("Legian",              8.5, 30, 7, 8.5, "Antara Kuta dan Seminyak, ramai wisatawan"),
    ("Nusa Penida",         6.5, 12, 2, 5.0, "Destinasi wisata berkembang, akses via kapal"),
    ("Tabanan",             6.0, 10, 2, 6.0, "Kota satelit, potensi pasar lokal, sewa murah"),
    ("Gianyar",             6.5, 12, 3, 6.5, "Dekat Ubud, pusat kerajinan & kuliner lokal"),
    ("Singaraja",           6.0, 10, 2, 6.0, "Kota terbesar di Bali Utara, pasar lokal besar"),
    ("Negara",              5.5,  8, 2, 5.5, "Ibu kota Jembrana, pasar lokal, sewa yang lumayan murah"),
    ("Jembrana",            5.0,  7, 1, 5.0, "Kabupaten barat Bali, kompetitor sangat sedikit"),
    ("Gilimanuk",           5.0,  6, 1, 5.5, "Pintu masuk Bali dari Jawa, potensi transit"),
    ("Klungkung",           6.0, 10, 2, 6.0, "Kota sejarah, satu kabupaten dengan Nusa Penida, pasar lokal"),
    ("Karangasem",          5.5,  9, 2, 5.5, "Bali Timur, wisata alam & budaya, berkembang"),
    ("Bangli",              5.0,  8, 1, 5.0, "Kabupaten tengah Bali, pasar lokal dengan kompetitor yang sepi"),
    ("Kintamani",           6.0, 10, 2, 5.5, "Wisata alam Gunung Batur, niche market"),
    ("Bedugul",             6.0, 11, 2, 5.5, "Wisata alam Danau Beratan, udara sejuk"),
]

DEFAULT_EDGES = [
    # (src, dst, jarak_km, bidirectional)
    ("Kuta",                "Seminyak",             4.0, True),
    ("Kuta",                "Legian",               2.0, True),
    ("Kuta",                "Jimbaran",             8.5, True),
    ("Kuta",                "Denpasar Barat",       7.0, True),
    ("Kuta",                "Denpasar Selatan",     6.5, True),
    ("Legian",              "Seminyak",             2.5, True),
    ("Legian",              "Kerobokan",            4.0, True),
    ("Seminyak",            "Canggu",               6.5, True),
    ("Seminyak",            "Kerobokan",            3.0, True),
    ("Canggu",              "Kerobokan",            4.5, True),
    ("Denpasar Barat",      "Denpasar Timur",       4.0, True),
    ("Denpasar Barat",      "Denpasar Selatan",     5.0, True),
    ("Denpasar Barat",      "Sanur",                6.5, True),
    ("Denpasar Barat",      "Tabanan",             22.0, True),
    ("Denpasar Timur",      "Denpasar Selatan",     6.0, True),
    ("Denpasar Timur",      "Sanur",                5.0, True),
    ("Denpasar Timur",      "Gianyar",             18.0, True),
    ("Denpasar Timur",      "Ubud",                25.0, True),
    ("Denpasar Selatan",    "Sanur",                7.0, True),
    ("Denpasar Selatan",    "Jimbaran",             9.0, True),
    ("Denpasar Selatan",    "Nusa Dua",            14.0, True),
    ("Sanur",               "Nusa Dua",            16.0, True),
    ("Sanur",               "Nusa Penida",          5.0, True),
    ("Jimbaran",            "Nusa Dua",             8.0, True),
    ("Jimbaran",            "Denpasar Barat",      12.0, True),
    ("Ubud",                "Sanur",               26.0, True),
    ("Ubud",                "Gianyar",             10.0, True),
    ("Ubud",                "Kintamani",           36.0, True),
    ("Kerobokan",           "Denpasar Barat",       7.5, True),
    ("Tabanan",             "Singaraja",           55.0, True),
    ("Tabanan",             "Bedugul",             35.0, True),
    ("Tabanan",             "Negara",              45.0, True),
    ("Gianyar",             "Klungkung",           18.0, True),
    ("Gianyar",             "Singaraja",           58.0, True),
    ("Klungkung",           "Karangasem",          35.0, True),
    ("Klungkung",           "Nusa Penida",         20.0, True),
    ("Karangasem",          "Bangli",              45.0, True),
    ("Bangli",              "Kintamani",           20.0, True),
    ("Bangli",              "Gianyar",             25.0, True),
    ("Kintamani",           "Singaraja",           50.0, True),
    ("Kintamani",           "Bedugul",             40.0, True),
    ("Bedugul",             "Singaraja",           50.0, True),
    ("Negara",              "Jembrana",            10.0, True),
    ("Negara",              "Gilimanuk",           25.0, True),
    ("Jembrana",            "Gilimanuk",           35.0, True),
    ("Jembrana",            "Tabanan",             55.0, True),

]